#!/usr/bin/env php
<?php

set_time_limit(0);

use Symfony\Component\Console\Application;

include __DIR__.'/ven   dor/autoload.php';

$app = new Application();

$container['generator.config'] = include 'config.php';

$app->addCommands([
        new Groovey\Generator\Commands\About(),
        new Groovey\Generator\Commands\Create($container),
    ]);

$status = $app->run();

exit($status);
