#!/usr/bin/env php
<?php

set_time_limit(0);

use Symfony\Component\Console\Application;

include __DIR__.'/vendor/autoload.php';

$app = new Application();

$app->addCommands([
        new Groovey\Generator\Commands\About(),
        new Groovey\Generator\Commands\Create(),
    ]);

$status = $app->run();

exit($status);
